package org.sporotofpoorety.eternitymode.util;


import net.minecraft.util.math.MathHelper;
import net.minecraft.util.math.Vec3d;

import org.sporotofpoorety.eternitymode.util.OrthonormalBasis;




public final class RotationUtil 
{

//Interpolate one direction towards another
    public static Vec3d rotateDirTowardsDir
    (
        Vec3d originalVec,
        Vec3d targetVec,
        double maxRotate   
    )
    {

//Normalize the directions
        Vec3d originalDir = originalVec.normalize();
        Vec3d targetDir  = targetVec.normalize();




//Get cos between the directions
        double cosBetweenDirs = originalDir.dotProduct(targetDir);
//Clamp cos to valid value
            cosBetweenDirs = MathHelper.clamp(cosBetweenDirs, -1.0D, 1.0D);
//Get angle (0 to π) using cos (1 to -1)
        double angleBetweenDirs = Math.acos(cosBetweenDirs);


//If directions are almost identical
        if (angleBetweenDirs <= maxRotate)
        {
//Just snap to target
            return targetDir;
        }




//Get cross product of the two dirs
        Vec3d dirsCrossProduct = originalDir.crossProduct(targetDir);

//Get and by default rotate around dirs perpendicular axis
        Vec3d axisForRotation = dirsCrossProduct.normalize();


//But if the dirs are practically opposite
        if (dirsCrossProduct.lengthSquared() < 0.001D)
        {
//Opposite = infinite possible rotations, 
//so i gotta pick an arbitrary perpendicular one
            Vec3d[] originalOrtho = OrthonormalBasis.makeOrthonormalBasis(originalDir);
//Arbitrarily pick original's ortho-right
            axisForRotation = originalOrtho[0];
        }




//NEED FOR RODRIGUES ROTATION


//Get cos and sin of rotation angle
        double cosOfRotation = Math.cos(maxRotate);
        double sinOfRotation = Math.sin(maxRotate);

//Get RotAxis  x  OrigVec
        Vec3d RotAxis_X_OrigVec  =  axisForRotation.crossProduct(originalDir);
//Get RotAxis  *  OrigVec
        double OrigVec_Dot_RotAxis =  axisForRotation.dotProduct(originalDir);




/*
NOW RODRIGUES ROTATION

Vrot 
= V*cos0  +  (Ar X V)sin0  +  Ar(V * Ar)(1 - cos0)
*/        


//Original vec lowered by
//how much the rotation angle is
        Vec3d remainsOfOriginal = originalDir.scale(cosOfRotation);


//Tangential force as generated by
//perpendicular direction scaled by sine of rotation
        Vec3d tangentialForce = RotAxis_X_OrigVec.scale(sinOfRotation);


//When original vec was lowered,
//the part of it that was already 
//parallel to the axis of rotation got lowered too, so restore what was lost
        Vec3d parallelPartToRestore = axisForRotation.scale(OrigVec_Dot_RotAxis).scale(1.0D - cosOfRotation);




//Add all 3 components to get final interpolated dir
        Vec3d finalInterpolatedDir = 
            remainsOfOriginal
            .add(tangentialForce)
            .add(parallelPartToRestore);




//One last normalize just to be sure
        return finalInterpolatedDir.normalize();

    }

}
